### ISSUE TITLE
DPF: Spike: Extended evaluation of server side blobs copy

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/DataSpaceConnector#101]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/618
Spike for feature https://github.com/agera-edc/DataSpaceConnector/issues/20

### Description
Follow up Spike after #25 to extend the evaluation for server side blobs copy.
In previous spike we evaluated the Azure Java SDK https://docs.microsoft.com/en-us/rest/api/storageservices/Copy-Blob and AzCopy. In this spike we want to explore another option to copy the blobs, to mirror the AzCopy behavior.
Additionally, we found some differences between the documentation and the real behavior of the REST API, which should be clarified.

[Results from Spike](https://github.com/agera-edc/DataSpaceConnector/blob/spike/25-blob-storage-in-place-copy/blobspike/README.md#copying-block-blob-in-chunks) #25 

Outcome of this spike will be used for story https://github.com/agera-edc/DataSpaceConnector/issues/26 implementation.

### Acceptance Criteria

- [ ] Open points in the understanding of blob copy operations in Java are clarified and documented

### Tasks
- [x] Clarify with Solution Area the best way to copy the blob programmatically in Java 
- [ ] [Internal issue created] Clarify with Solution Area the following points in the [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) 
    - [ ] 256 MB size limit for the copied blob (when testing the client we didn't encounter this limitation) 
    - [ ] synchronous behavior of the copy operation (we observed that the call is asynchronous when using it)
- [x]  Code spike the perform the copy by aggregating [PUT block blobs operations](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-from-url). More information in the [spike doc](https://github.com/agera-edc/DataSpaceConnector/blob/spike/25-blob-storage-in-place-copy/blobspike/README.md#copying-block-blob-in-chunks).
- [x] Document the results.
- [x] Update story #26 and #27 based on insights and remove refinement tag.
