### ISSUE TITLE
DPF: Spike: Azure Data Factory

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#106]
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/773
Feature: https://github.com/agera-edc/DataSpaceConnector/issues/20

Azure Data Factory offers a serverless way to copy data at scale in an optimised manner, with increased scalability and reducing the operational load on the application when copying data.

ADF cannot replace DPF (EDC customers may not want a dependency on Azure, and ADF does not support e.g. copying to S3), but it could be an optional module in DPF. DataFlowRequests could be routed to either ADF or "standard DPF" depending e.g. on transfer size and destination.

Advantages of ADF include:
- Optionally deploy Integration Runtime to access data within enterprise network (or even on-prem)
- High scalability and parallelism
- Optimized copy e.g. for blobs
- Built-in reliability mechanisms, retry, monitoring
- 80+ connectors, for example S3, Azure storage
- Flexible handling of many scenarios when copying from blob e.g. "single file" / "full folder" / "wildcards" / 'flatten hierarchy" etc
- Data transformation - not in scope at the moment, but perhaps in the future we want to land the data in the format the user requests it e.g. Parquet

## Acceptance Criteria

- [x] Spike code shows how a DPF DataFlowRequest can be executed on ADF
- [x] ADR detailing how ADF could be integrated, pros and cons

## Tasks

- [x] Spike using ADF SDK code to perform a transfer
- [ ] Write ADR
