### ISSUE TITLE
Engineering Fundamental Metrics - Trends

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#109]
Feature #29 

### Description

Follow-up story for #43 to add visualizations on how metrics change over time, to measure improvements. 

Note: CodeCov reports can be found here and already support the required charts: https://app.codecov.io/gh/eclipse-dataspaceconnector/DataSpaceConnector/

### Acceptance Criteria

- [x] Metrics defined in #43 are reviewed and metrics that are not implemented yet but required are added
- [x] The EF report supports chats for individual metrics based on a selectable time frame

### Tasks

- [x] Review current metrics and decide if additional metrics are needed
- [x] Add number of PRs (by contributing party) over time to the PowerBI report
- [x] Create a dashboard in ADO (CodeHub) to pull together data from the PowerBI report and from CodeCov
- [ ] ~~Ignore PRs with label `on hold`~~

**Comment by zeier** [comment]
Discussed with @chrislomonico that capturing linting errors and number of rejected PRs don't provide much value at the current stage and should be skipped.
