### ISSUE TITLE
Metrics: Instrument state machine ExecutorServices

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#113]
Story for Feature #40
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/790

## Description

#35 introduced instrumentation for ExecutorService, although only for `HealthCheckServiceImpl`. This story is about extending the instrumentation of ExecutorServices within EDC to include other interesting candidates:

- ContractNegotiationManager
- TransferProcessManager
- Command Watchdog
- Oauth2Extension
- DPF

Some of the listed examples use single thread executors with an endless loop that will require to be migrated to scheduled executors.

## Acceptance Criteria
- [x] Agreement on which ExecutorServices are worth instrumenting with the EDC community
- [x] ExecutorServices are instrumented

## Tasks
- [x] Agree which ExecutorServices are to be instrumented
- [x] Instrument ExecutorServices
- [x] Extend Integration Tests #105 if applicable

**Comment by algattik** [comment]
@marcgs I believe it also means changing endless loops to scheduled executors

**Comment by zeier** [comment]
Assigning to @marcgs to add EDC issue.
