### ISSUE TITLE
Investigate java-potentially-weak-cryptographic-algorithm CodeQL alerts

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/DataSpaceConnector#114]
## Description
Follow up story for issue #41 
During the story #41  6 alerts related to **Use of a potentially broken or risky cryptographic algorithm** were dismissed. This story aims to investigate if the alerts can stay dismissed or they require some actions/fixes.

More information about the CodeQL alert: https://codeql.github.com/codeql-query-help/java/java-potentially-weak-cryptographic-algorithm/

Link to the alerts in the internal edc-agera repo: [CodeQL scan results on main branch](https://github.com/agera-edc/DataSpaceConnector/security/code-scanning?query=is%3Aopen+branch%3Amain+severity%3Ahigh)

Places in the code where the alert was raised:

extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/key/KeyPairFactory.java:43
![Screenshot 2022-02-28 at 17 42 13](https://user-images.githubusercontent.com/4217554/156023844-4b9eb027-5e4b-41c7-bd64-f1353a3f052d.png)

extensions/iam/decentralized-identity/identity-did-crypto/src/main/java/org/eclipse/dataspaceconnector/iam/did/crypto/key/KeyPairFactory.java:65
![Screenshot 2022-02-28 at 17 42 22](https://user-images.githubusercontent.com/4217554/156023872-eb33c1c9-3d1a-4aca-9dea-b9aa17f57522.png)

extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/hub/message/JsonCommitObject.java:81
![Screenshot 2022-02-28 at 17 42 40](https://user-images.githubusercontent.com/4217554/156023896-fff5e570-39e2-4d9b-9fee-8a4de775fe5a.png)

extensions/iam/oauth2/oauth2-core/src/main/java/org/eclipse/dataspaceconnector/iam/oauth2/core/jwt/Fingerprint.java:55
![Screenshot 2022-02-28 at 17 42 54](https://user-images.githubusercontent.com/4217554/156023918-6cf4d612-4945-4a41-b98b-9270df150019.png)

extensions/ion/ion-core/src/main/java/org/eclipse/dataspaceconnector/ion/util/MultihashHelper.java:47
![Screenshot 2022-02-28 at 17 43 32](https://user-images.githubusercontent.com/4217554/156023927-f46391e6-a9e9-42b7-8def-c03d383c6784.png)

Note that the code could have changed after the scan was performed. 

## Acceptance Criteria
- [ ] Above mentioned CodeQL alerts are fixed or stay dismissed
- [ ] In case the alerts stay dismissed the reasoning behind that decision is documented

## Tasks
- [ ] Investigate if the alerts need to be fixed in the code
- [ ] Fix the alerts if applicable
- [ ] Document the reasoning behind dismissing the alerts (code comments or ADR) if applicable
- [ ] Create follow up issues if needed
