### ISSUE TITLE
DPF: serverless transfer with Data Factory

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#115]
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/773
Feature: https://github.com/agera-edc/DataSpaceConnector/issues/20

## Description

Implement DPF copy with Azure Data Factory (ADF) per #106.

- Supported stores: in this implementation, implement only blob source and blob sink
- Routing between transfer strategies: in this implementation, use a simple first-in-classpath strategy
- Wait for completion: use busy polling, until DPF implements a state machine loop
- System testing: Run tests on Azure, after merge in upstream main (as access to secrets is needed)

## Acceptance Criteria
- [ ] EDC runtime can optionally include a Data Factory extension to perform transfers with ADF
- [ ] System test verifies Data Factory extensions on Azure after merge to upstream main

## Tasks
- [ ] Refactor DPF to introduce a pluggable TransferService, of which the existing PipelineService is one implementation
- [ ] Create a data factory extension, with TransferService for blob to blob copy
- [ ] Create Terraform code to deploy Data Factory, Key Vault and Storage Accounts
- [ ] Create system test that performs data transfer in Azure
- [ ] Provision AZURE_CREDENTIALS secret in upstream repo (service principal)
- [ ] Create pipeline that runs Terraform and system test on merge to main, if AZURE_CREDENTIALS secret exists

**Comment by algattik** [comment]
Follow up items:
- async polling
- clean up data factory pipeline and assets after run

**Comment by cpeeyush** [comment]
Upstream PR published https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/910
