### ISSUE TITLE
Spike - Maven Central Snapshots

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#121]
Feature #116 
Before #122

## Description

With Feature #116 we want to publish EDC artifacts as `SNAPSHOT` to Maven Central.

The goal of this spike is to get a solid understanding on what is involved to publish artifacts, including required accounts, authentication, metadata, version number for the snapshot and whether it is possible to have named snapshots.

## Acceptance Criteria

- [x] We know how we can publish artifacts to Maven Central
- [x] Governance topics are clarified with Markus S.
- [x] Stories for feature #116 are updated with insights gained from this spike

## Tasks

- [x] Investigate necessary actions to be carried out for publishing to Maven Central
- [x] Document findings from investigation
- [x] Update [Issue](#122) `Tasks` based on findings
- [x] Create any necessary follow-up issues
~~Create EDC Issue with all relevant information from findings~~

## Note: EDC issue will be created with Markus after we sync on the deployment (2022.03.30)
