### ISSUE TITLE
Artifact Management - Quality Gate

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#123]
Feature #116 
After #122  

**Note: This story could be merged with #122 if that's easier for the team to work with, decision pending**

## Description

A quality gate including a verification build should be implemented before publishing EDC artifacts to Maven Central (see #122) to ensure a baseline level of quality. 

## Acceptance Criteria

- [ ] Artifacts are only published from `main` if a corresponding quality gate incl. validation build passes
- [ ] All automated tests are run as part of the validation build
- [ ] Artifacts can only be published by committers

## Tasks

- [ ] TODO

**Comment by chrislomonico** [comment]
Not in a state until #121  is completed for task out

**Comment by zeier** [comment]
Merged with #122
