### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#13]
This feature is to track the work done for setting up and getting started, Also it will be home for Collaboration work.

- [x] agera-edc/DataSpaceConnector#14 
- [x] agera-edc/DataSpaceConnector#15 
- [x] agera-edc/DataSpaceConnector#16 
- [x] agera-edc/DataSpaceConnector#17 
- [x] agera-edc/DataSpaceConnector#18 
- [x] agera-edc/DataSpaceConnector#19
