### ISSUE TITLE
Observability Sample with Azure Monitor

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#131]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/861
Feature #130 

## Description

To operate solutions based on the EDC on Azure, it is required that observability features provided by #40 integrate well with Azure Monitor.

This story will provide a sample (or extend sample 4.3) with step by step instructions on how to integrate with Azure Monitor.

There are some gaps to be expected when feeding logs into Azure Monitor, and potentially others. Investigating such gaps and closing them is within the scope of this story. Larger gaps should be addressed with separate stories.

## Acceptance Criteria
 
- [ ] Distributed tracing, metrics and logs can be fed into and visualized in Azure Monitor
- [ ] A sample is available with step by step examples on how to integrate with Azure Monitor
- [ ] Missing pieces to have a complete integration with Azure Monitor are implemented as part of this story or split out to separate stories

## Tasks

- [ ] Decide whether a new sample is required or whether we can extend sample 4.3
- [ ] Create sample for observability with Azure Monitor according to the AC listed above

**Comment by zeier** [comment]
@marcgs @Izzzu upstream issue is added
