### ISSUE TITLE
Azure Monitor Demo Recording

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#132]
Feature #130 
After #131

## Description

Based on the sample for Azure Monitor Integration provided by #131, we want to record a demo to better convey and showcase the seamless integration of the EDC with Azure Monitor. Target audience are EDC users.

## Acceptance Criteria

- [x] Azure Monitor demo recording for EDC users is available
- [x] Developers watching the video will know what to do to set up Azure Monitoring with the EDC
- [x] The demo showcases the smooth integration of the EDC with Azure Monitor
- [x] Recording is uploaded to the EDC YouTube channel
- [x] The demo highlights the observability challenges of distributed systems as an introduction and shows how these challenges are addressed with the EDC and Azure Monitor
- [ ] ~As part of the demo, a data transfer with the Data Plane running in a separate process is performed, as an example use case for distributed tracing~

## Tasks

- [x] Record demo
- [x] Review demo with Jim/Paul
- [x] Upload demo to YouTube channel

## Notes
2022.04.06 - Iza is interested; waiting for return of the Max to sync on what expectations for YouTube (future) stars is

**Comment by zeier** [comment]
Closing this one down, as all acceptance criteria are met, and the video is published.

**Comment by zeier** [comment]
Published recording: https://www.youtube.com/watch?v=Mu7CJa028dE
