### ISSUE TITLE
DataManagementApi - Transfer Process

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#141]
Feature #118 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/809
After #135 and #154

## Description

Implementation according to upstream issue 809.

Note that upstream issues 805, 806, 807 and 808 will be implemented by Andrea and Diego, we should coordinate our implementation with them and mutually review the corresponding PRs to be aligned.

## Acceptance Criteria

- [ ] Implementation according to the upstream issue is completed
- [ ] Implementation is aligned with the implementation of upstream issues 805, 806, 807 and 808

## Tasks

- [ ] Implementation according to the description in upstream issue
- [ ] Review PRs for upstream issues [805](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/805), [806](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/806), [807](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/807) and [808](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/808) to be aligned with the implementation of the other services.
- [ ] Unit tests

**Comment by algattik** [comment]
See PRs for blocking upstream items
