### ISSUE TITLE
DPF Transfer with Azure Monitor Recording

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#142]
Feature #49
After #161, #173

## Description

Create a recording for the CPR demo showcasing DPF with either the Azure Storage Extension #20 or the Azure Data Factory Extension #115 . Azure Monitor #130 should be used as a driver to show how requests navigate through the system.

Proposed script:
- Initiate a contract negotiation
- Visualize contract negotiation trace with Azure Monitor focusing on the consumer-provider communication
- Initiate a transfer with DPF
- Visualize transfer process trace with Azure Monitor focusing on the different components interacting together.
- Initate a transfer that runs into an error
- Visualize trace and logs for the error in Azure Monitor
- Visualize metrics gathered with Azure Monitor

## Acceptance Criteria

- [x] A scenario is prepared to showcase the aforementioned functionality together (#20, #115 and #130)
- [x] A recording is ready that can be used for the CPR 

## Tasks

- [x] Create a recording showcasing EDC working together with DPF
- [x] Review recording with the team and include feedback
- [x] Recording is used for the CPR

**Comment by marcgs** [comment]
Blocked until #173 is finished

**Comment by zeier** [comment]
@marcgs, closing this item as the last task is completed and acceptance criteria are met.
