### ISSUE TITLE
Data Management API - `TransferProcessStore` SQL Implementation

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#154]
Feature #118 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/865
After #135 and #136
Before #141 

⚠️[ Technical proposal](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/899) for TransferProcessStore based on SQL  needs to be accepted/merged first.

## Description

Implementation according to upstream issue 865.

- `extensions/sql/common` can be reused for SQL Implementation.
- Use PostgreSQL for SQL implementation.

## Acceptance Criteria

- [ ] Upstream issue is completed

## Tasks

- [ ] Create schema as propose in upstream PR 899.
- [ ] Provide SQL implementation of `TransferProcessStore` interface. See upstream issue and technical proposal PR 899 for details.
- [ ] Add integration tests for SQL implementation. (Test containers can be used ? )
- [ ] Update In-memory implementation of `TransferProcessStore` to use H2 Database (e.g. `extensions/sql/common/src/test/java/org/eclipse/dataspaceconnector/sql/SqlQueryExecutorIntegrationTest.java`).

**Comment by zeier** [comment]
This story (upstream issue) will be picked up by Paul.
