### ISSUE TITLE
Cosmos DB Cloud Tests

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#170]
Feature #150 
Upstream issue: [#845](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/845)

## Description

Azure Cosmos DB emulator has intermittent failures during CI runs and causes PR checks to fails intermittently. To avoid this issue a proposed solution is:

- Run cosmos db test on cloud infra if a cosmos instance is available.
- Otherwise run it using windows based cosmos db emulator. (⚠️ test running against emulator can fail due to its performance issues, it should be highlighted in docs)

(Similar approach ([Federated access](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows)) can be used as did in run Azure Data Factory integration tests with Azure environment check in [PR](https://[github.com](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/910)/eclipse-dataspaceconnector/DataSpaceConnector/pull/910))

## Acceptance Criteria

- [ ] Cosmos DB Integration tests execute on cloud instance if respective environment is available.
- [ ] Cosmos DB Integration tests execute on local emulator if cloud environment is not available.
- [ ] EDC upstream repo configured to use Cosmos DB cloud instance. (Take help from Jim/Paul for this)
- [ ] Update docs to mention approach and limitation of cosmos db emulator.

## Tasks

- [ ] Setup cloud cosmos DB instance for Agera repo.
- [ ] Setup [Federated access](https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows) on agera repo.
- [ ] Update integrationTests workflow to use cloud instance when available otherwise use local emulator for cosmos db tests.
- [ ] Validate integration tests runs well on cloud instance(when available) and local emulator.
- [ ] Configuration upstream repo to use Cosmos DB cloud instance. (Take help from Jim/Paul for this)
- [ ] Agera cosmos db instance can be removed as it can continue using emulator to save cost.

**Comment by zeier** [comment]
Assigning to @cpeeyush to add information discussed during BL refinement.

**Comment by cpeeyush** [comment]
It would be good to also check what was there before emulator was introduced. If that option is simpler and cleaner then we might take that one.

**Comment by algattik** [comment]
Per discussion this was implemented more simply, with secrets rather than federated identity.

**Comment by chrislomonico** [comment]
@algattik have the tasks been completed or are they skipped? If completed, please indicate them (checking them off) or if they are part of a follow-up issue/removed, please indicate such

**Comment by algattik** [comment]
Updated.
