### ISSUE TITLE
Application of Test Categorization

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#171]
EDC upstream issue [#819](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/819)
Feature #150

## Description

PR [868](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/868) introduced use of Junit Tags to run Integration tests. 

To further classify the different kinds of tests use proposed tags in [upstream issue](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/819) and add gradle tasks to run tests related to tags mentioned in upstream issue only.

(if needed Paul can help in order to understand which test belongs to which tag category)

## Acceptance Criteria

- [ ] Tests categorized using proposed tags.
- [ ] Added gradle task related to proposed tags.
- [ ] Update integration-test doc to describe use of tags to categorize different type of tests.

## Tasks
Same as acceptance criteria.

**Comment by chrislomonico** [comment]
closing per upstream status
