### ISSUE TITLE
Integration Testing of Distributed Tracing

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#172]
Story for Feature #40
Upstream: #788

## Description
As an EDC user, I would like to have guarantees that the distributed tracing is working properly.

## Acceptance Criteria
- [ ] Correct functioning of distributed tracing in EDC is covered by tests

## Tasks
- [ ] Investigate and implement appropriate approach to test tracing:
   - [ ] Run an integration tests with a [custom OpenTelemetry exporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java) to capture and verify traces. This is the preferred approach as it would prevent from the need to use a third party system for integration testing and would allow for a more efficient inner loop.
   - [ ] Run an E2E test to gather telemetry and push results to Jaeger. Evaluate using a docker-compose approach as in sample 4.03 VS using @EdcRuntimeExtension and starting Jaeger separately. Use the [Jaeger API](https://www.jaegertracing.io/docs/1.31/apis/) to verify traces.

**Comment by ouphi** [comment]
Upstream PR: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1035
