### ISSUE TITLE
Retro follow up: Update team working agreement

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#18]
Story for feature agera-edc/DataSpaceConnector#13 

### Description
We had two action items from the retro on Feb 09, 2022. First one was about making the meetings more efficient. Second one was about assigning a scrum lead. This story is to update the team working agreement with the first action item.

### Acceptance Criteria

- [x] Update team working agreement
  - [x] Send out  material in advance
  - [x] Make a suggestion to the topic that you schedule the meeting for 
  - [x] Start a conversation in Teams before planning a meeting sharing material in advance
  - [x] PL should be optional, and needs to be written down so the team can relate

### Tasks

- [x] Prepare draft
- [x] Team Collaboration
- [x] Wrap up
