### ISSUE TITLE
Spike: CI duration

### ISSUE THREAD

**Issue by ouphi** [agera-edc/DataSpaceConnector#187]
Feature #194
After #171, #223

## Description
The goal of this Spike is to analyse the duration of CI. 
Evaluate:
- What are the core factors increasing CI durations
- What test category take more time

The second part is to evaluate solutions to reduce the duration.

Considerations:
- As discussed in https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1000#discussion_r841413437 it would be good to migrate usages of `setup-java` action to the [gradle-build](https://github.com/gradle/gradle-build-action#why-use-the-gradle-build-action) action. Consider this in the improvement analysis.

## Acceptance Criteria
- [ ] A report to understand CI duration is provided.
- [ ] Potential solutions to reduce the duration are evaluated and documented.
- [ ] Working solutions can be proposed and corresponding stories are created.

## Tasks
Same as acceptance criteria.

**Comment by algattik** [comment]
See also https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/840

**Comment by algattik** [comment]
Should we do this only after #203 , so that we have test report as data source?

**Comment by ouphi** [comment]
Created this issue: https://github.com/agera-edc/DataSpaceConnector/issues/224

**Comment by zeier** [comment]
CI times are currently reasonable and don't require further investigation.
