### ISSUE TITLE
Identification of Valuable Performance Tests

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#191]
Feature #28 
Upstream (in part) https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1296

## Description

As discussed during CPR we would like to identify performance tests that we think are valuable to be implemented (e.g. where we expect performance issues or high likelihood of performance regressions) and file corresponding upstream issues for the EDC community to be picked up.

One example has already been filed in upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/838

## Acceptance Criteria

- [x] Identified tests are reviewed with Jim or Paul (they might have additional tests that come to mind)
- [x] Upstream issues for valuable performance tests are filed
- [x] Upstream issues contain references to the corresponding tooling defined in previous stories (#81, #60)

## Tasks

- [x] Identify and document valuable performance tests to be implemented.
- [x] Validate the tests with Jim or Paul.
- [x] Create related upstream issues.

**Comment by algattik** [comment]
Additional coverage needed was implemented in existing test through PR
