### ISSUE TITLE
DPF/Testing: Integration Testing for DPF Http Extension

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#22]
Story for feature agera-edc/DataSpaceConnector#20 

### Description
As a consumer of the Data plane feature I would like to have a stable implementation of DPF HTTP extension so that I can reliably use it.

DPF implementation (contains DPF HTTP extension with unit tests ) PR has been merged [EDC repo PR #639](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/639)

### Acceptance Criteria
- [x] DPF integration testing strategy is defined. (reuse the work done under agera-edc/DataSpaceConnector#37  to get source/sink embedded runtimes)
- [x] DPF HTTP extension has integration test coverage as per CSE standards.
- [x] Tests are being executed to validate a build.
- [x] Integration testing approach is document for HTTP extension.

### Tasks

- [x] Integration test with 2 HTTP endpoints (source and sink) that moves data in between them(happy path).
- [x] Integration test to simulated failure scenarios. 
     - Need to check approach with Jim on how to simulate failures and possible failures scenarios e.g. one of http endpoint become unavailable at the beginning of data transfer or in the middle of a data transfer. 
- [x] Update CI pipeline to run tests.
- [x] Update documentation about these tests and how to execute them.

**Comment by cpeeyush** [comment]
EDC PR https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/758

**Comment by cpeeyush** [comment]
EDC PR merged.
