### ISSUE TITLE
Composite Action to Set Up Gradle

### ISSUE THREAD

**Issue by ouphi** [agera-edc/DataSpaceConnector#224]
upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1159
Feature #194 

# Feature Request

- Use a composite action to setup gradle
- Use `gradle-build-action` instead of `java-setup` with cache: 'gradle' in CI/CD.

## Which Areas Would Be Affected?
CI CD

## Why Is the Feature Desired?
- Creating a composite action to setup gradle would avoid repeating configs like distribution and java-version in different places.

- Using gradle-build-actions has [benefits](https://github.com/gradle/gradle-build-action#why-use-the-gradle-build-action).
More sophisticated and more efficient caching of Gradle User Home between invocations, compared to setup-java and most custom configurations using actions/cache. [More details below](https://github.com/gradle/gradle-build-action#caching).

# Acceptance criterias
- [ ] A composite action is created replaces usage of gradle-build-action and java-setup/
- [ ] `gradle-build-action` is used in the composite action.

# Tasks
- [ ] Create a composite action using [gradle-build-action](https://github.com/gradle/gradle-build-action) to setup gradle.
- [ ] Replace usage of gradle-build-action and java-setup with the composite action.
