### ISSUE TITLE
DPF: Azure Object Storage Extension - Simple Data Movement

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#23]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/618

Story for feature agera-edc/DataSpaceConnector#20 

### Description
EDC consumers and/or providers may want data to be consumed from and/or moved to Azure storage blob. The DPF should support moving such data at scale. While later we want to optimize with parallelism and scale-out, the first step should be to support simple data movement (including end-to-end testing to support later refactoring).

### Acceptance Criteria

- [x] Extend the existing DPF Transfer function controller to:
  - [x] read data from Az storage blob.
  - [x] write data into Az storage blob.
  - [x] Azure SDK streams operations are used to perform data operations. This will support large datasets as well.
- [x] Integration testing. 
- [x] Tests are being executed to validate a build.

### Tasks

- [x] Create Azure Blob Storage extension module. Under [data-plane](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/feature/data-plane-framework/extensions/data-plane) e.g. data-plane/azure/blob-storage
- [x] Provide DataSink implementation for Azure Blob Storage.
- [x] Provide DataSource implementation for Azure Blob Storage.
- [x] Provide DataSourceFactory implementation to create Azure Blob Storage DataSource.
- [x] Provide DataSinkFactory implementation to create Azure Blob Storage DataSink.
- [x] Add documentation to explain the functionality and usages of this extension.
- [x] Unit and Integration test(when actual storage instance is needed [Azurite](https://github.com/Azure/Azurite) is preferred over cloud infra) coverage.
- [x] Update CI pipeline to run tests.
