### ISSUE TITLE
End-to-end blob storage transfer is not working

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#231]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1183
After #235, #236

## Description

End-to-end flow for managing configuration and credentials for blob storage transfers is not working. Integration tests exist in the separate layers, but the end-to-end flow is not functional. One issue is that there are two classes named AzureBlobStoreSchema with different properties inside (#235).

While investigating the problem, it also appeared that documentation to understand how the system should work is missing.
- How the `managedResources` attribute is used
- What kinds of keys are used/transferred (shared access key vs. short-lived SAS)
- How vaults are used

AzureStorageDataSourceFactory should call `vault.getSecret(dataAddress.getKeyName())` instead of `dataAddress.getProperty(AzureBlobStoreSchema.SHARED_KEY))`

## Acceptance Criteria

- [x] ADR to describe blob transfer end-to-end flow approach and details.
- [x] End-to-end test to verify blob data transfer (managedResources=true).
- [x] Test runs as part of CI.
- [x]  Update docs.

## Tasks

- [x] ADR on blob transfer end-to-end flow.
- [x] Add new end-to-end test to verify blob data transfer using DataManagement APIs
- [x] Update README(extensions/azure/data-plane/storage/README.md)

**Comment by algattik** [comment]
Requires 4 upstream PRs to be merged
