### ISSUE TITLE
TransferProcess API: provide provisioned resource information

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#237]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1208

## Description

When performing a transfer to Azure blob with `managedResources=true`, the consumer EDC provisions a storage container with a randomly generated name. The container is used as destination of the data copy on the provider DPF.

The client polls the TransferProcess API for completion. When the transfer is completed, the client can access the data in the storage container. However, the client currently has no way of knowing what storage container was created by the consumer provisioner. 

## Acceptance Criteria

- [x] API client can get information about provisioned resources, containing at least the storage container name

## Tasks

- [x] Work with Paul to determine how to design the API changes
- [x] Implement changes and UT
