### ISSUE TITLE
DPF - Azure Object Storage Extension - Simple Data Movement

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#24]
Story for feature agera-edc/DataSpaceConnector#20 

### Description
EDC consumers and/or providers may want data to be consumed from and/or moved to Azure storage blob. The DPF should support moving such data at scale. While later we want to optimize with parallelism and scale-out, the first step should be to support simple data movement (including end-to-end testing to support later refactoring).

⚠️ DPF implementation(contains DPF HTTP extension with unit tests ) PR needs to be merged [EDC repo PR #496](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/496)

### Acceptance Criteria

- [ ] Extend the existing DPF Transfer function controller to:
  - [ ] read data from Az storage blob.
  - [ ] write data into Az storage blob.
  - [ ] Azure SDK streams operations are used to perform data operations. This will support large datasets as well.
- [ ] Integration testing. 
- [ ] Tests are being executed to validate a build.

### Tasks

- [ ] Create Azure Blob Storage extension module. Under [data-plane](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/tree/feature/data-plane-framework/extensions/data-plane) e.g. data-plane/azure/blob-storage
- [ ] Provide DataSink implementation for Azure Blob Storage.
- [ ] Provide DataSource implementation for Azure Blob Storage.
- [ ] Provide DataSourceFactory implementation to create Azure Blob Storage DataSource.
- [ ] Provide DataSinkFactory implementation to create Azure Blob Storage DataSink.
- [ ] Add documentation to explain the functionality and usages of this extension.
- [ ] Unit and Integration test(when actual storage instance is needed [Azurite](https://github.com/Azure/Azurite) is preferred over cloud infra) coverage.
- [ ] Update CI pipeline to run tests.

**Comment by algattik** [comment]
Duplicate with #23
