### ISSUE TITLE
Fix ADF integration in EDC

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#240]
## Description
DPF integration with ADF seems to be broken with the latest main change. 

(PR for ADF implementation https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/910) 

## Acceptance Criteria
 - [x] An E2E tests verifies that ADF integration in EDC is working properly
 - [x] Fixes as required to make ADF integration work

## Tasks
 - [x] Create .complete file in provider side, once ADF pipeline is finished
 - [x] Use SAS instead of SAK in the ADF pipeline
 - [x] Run Blob system test from feature/1183/231-azure-e2e-test
 - [x] Report on any other issues
 - [x] Take latest work from https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1245/

**Comment by cpeeyush** [comment]
Merged https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/910
