### ISSUE TITLE
Spike: Data Management API Client

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#247]
Feature #194 
Upstream  https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1204, https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1264 

## Description

A generated client for the DataManagementAPI as proposed by https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1205 shall be introduced.

## Acceptance Criteria

- [x] Scope of upstream issue https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1205 is covered with feasibility spike

## Tasks

- [x] Develop a REST client module with generated code from the OpenAPI definition
- [x] Use REST client module in system tests (except those using Gatling, which are not compatible)
- [x] Fix Java types that are incompatible with OpenAPI definition, if possible
- [x] Update upstream issues with spike results

**Comment by algattik** [comment]
Blocked by upstream issue 1264. While we did a spike that showed the client working in one simple case, it breaks with complex JSON types
