### ISSUE TITLE
DPF: Spike: Azure Blob Storage In Place Copy

### ISSUE THREAD

**Issue by cpeeyush** [agera-edc/DataSpaceConnector#25]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/618
Spike for feature agera-edc/DataSpaceConnector#20

### Description
Spike to evaluate possibilities of copy-in-place when the source and sink are both Azure Blob Storage. Outcome of this spike will be used for story agera-edc/DataSpaceConnector#26 implementation.

AWS has a copy-in-place possibility for items stored in S3 buckets. See  [java SDK](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/CopyObjectRequest.html) and [user guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/copy-object.html) .

### Tasks
- [x] Evaluate if an Azure Blob can be copied in place between different Azure tenants/subscriptions. - Priority 1
- [x] Evaluate if an Azure Blob can be copied in place within same container.
- [x] Evaluate if an Azure Blob can be copied in place within same storage account but different containers.
- [x] Evaluate if an Azure Blob can be copied in place between different storage accounts within same Azure tenant/subscription.
- [x] Evaluate Integration testing approach. (when actual storage instance is needed [Azurite](https://github.com/Azure/Azurite) is preferred over cloud infra).
- [x] Evaluate observability of copy-in-place operations and make sure it is traceable.
