### ISSUE TITLE
Automated Tests for Sample 04.1

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#254]
Feature #194
After #252 

Upstream: [Automated Test for Sample 04.1 (File Transfer Listener) #1535](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1535)

## Description

Automated integration tests that run in CI should be added for samples to prevent the samples breaking due to changes in the EDC.

The scope of this story is to add automated integration tests for sample 04.1.

_Note: it was decided that EDC integration tests should not rely on samples. However, it is desirable to have additional tests to make sure that the samples don't get broken._

## Acceptance criteria 

- [x] Automated tests run in CI.

## Tasks

- [x] Create related an issue in upstream repository
- [x] Verify sample matches current architecture of EDC
- [x] Add integration test for sample
- [x] Integrate integration test into CI

**Comment by pkirch** [comment]
feature branch: https://github.com/agera-edc/DataSpaceConnector/tree/feature/1535-automated-tests-sample-041
sub-feature branch: https://github.com/agera-edc/DataSpaceConnector/tree/feature/1535/254-automated-test-sample-041
