### ISSUE TITLE
DPF: Azure Object Storage Extension - Server Side Copy

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#26]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/618

Feature #127 

⚠️ Currently on hold as it might not be needed, since we use Azure Data Factory (see #115).

### Description
Optimization to server-side copy when the source and sink are both Azure Blob Storage.

Quote from [Data Plane Framework #463](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/463):
> The DPF design is based on a pull streaming model; a `DataSink` pulls data from a `DataSource`. This allows the sink to control the rate of transfer and potentially parallelize operation. Moreover, optimizations can be made such as copy-in-place when the source and sink are the same infrastructure such as object storage hosted by a single cloud provider.

Docs from spike #25 and #101: https://github.com/agera-edc/DataSpaceConnector/tree/spike/25-blob-storage-in-place-copy/blobspike

### Acceptance Criteria

- [ ] The existing DPF Azure Object Storage Extension supports server-side copies
- [ ] End-to-end test on cloud infra.

### Tasks
- [ ] Modify the extension to provide server side copy using the [Azure Storage Java SDK BlockBlobClient](https://docs.microsoft.com/en-us/java/api/overview/azure/storage-blob-readme?view=azure-java-stable) using the logic described in t[he Spike doc](https://github.com/agera-edc/DataSpaceConnector/blob/spike/25-blob-storage-in-place-copy/blobspike/ADR.md)
    - consider using AsyncBlockBlobClient 
- [ ] E2E test with cloud infrastructure
- [ ] Update DPF documentation if needed

**Comment by zeier** [comment]
Removed the refinement tag, mentioned in #101 that this story needs to be updated based on spike outcomes.

**Comment by zeier** [comment]
Not planned to cover this item by the Agera crew until end of August.
