### ISSUE TITLE
CI: Verify OpenAPI generated spec files

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#266]
Feature #194 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1238

## Description

Repository contains OpenAPI YAML definitions generated from files. These must be manually updated and can go out of sync.

## Acceptance Criteria

- [x] Upstream issue is covered
- [x] Build fails with clear diff if OpenAPI definitions are out of sync

## Tasks

- [x] Make OpenAPI output reproducible
- [x] Update CI to fail if OpenAPI generated output doesn't match committed files
