### ISSUE TITLE
Core: standardize the use of Clock

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#284]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1364

Standardize the use of `Clock` in the codebase, rather than constructs like `Instant.now()` which cannot be mocked easily. The `Clock` could be provided centrally.

## Acceptance criteria
- [x] No use of `new Date()`, `Instant.now()` or similar in runtime code.
- [x] Single instance of `Clock` in shared context, also used for mocking.
- [ ] ADR

## Tasks
- [x] Create Single instance of `Clock` in shared context
- [x] Replace use of `new Date()`, `Instant.now()` or similar in runtime code, with shared `Clock`

**Comment by algattik** [comment]
Two PRs were merged upstream, ADR PR is still outstanding
