### ISSUE TITLE
Observability: Metrics: Micrometer instrumentation and bindings

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#35]
Corresponding EDC issue: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/419

For automatically collecting and exposing metrics, use Micrometer as documented at [Micrometer Metrics spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/blob/spike/micrometer-metrics/METRICS.md)

### Description
As an EDC developer I would like to have relevant metrics data so that I can debug malfunctions during the operations.

### Acceptance Criteria

- [x] Agreement with EDC community on tooling for code instrumentation
- [x] Agreement with EDC community on essential metrics to monitor
- [x] Implement EDC support for essential metrics with selected tooling
- [x] Documentation on decisions and implementation

### Tasks

- [x] Discussion with Jim to agree on the approach and on the Micrometer library dependency. Agree on which module will declare the Micrometer dependency.
- [x] ADR on metrics based on [OpenTelemetry Metrics spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/blob/spike/opentelemetry-metrics/METRICS.md), [Micrometer Metrics spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/blob/spike/micrometer-metrics/METRICS.md), [JMX Metrics spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/blob/spike/jmx-metrics/METRICS.md)
- [x] Set up a sample showing Micrometer based metrics collection in Prometheus. The sample README file explains how to modify the config to use Azure Application Insights agent instead
- [x] Implement Micrometer binding with essential metrics such as JVM, uptime, processor. Use Spring Actuator and Java Application Insights agent source code as inspiration to determine the exact bindings
- [x] Implement Micrometer binding with [Jetty](https://javadoc.io/static/io.micrometer/micrometer-core/1.5.3/io/micrometer/core/instrument/binder/jetty/JettyConnectionMetrics.html) and Jersey to automatically collect inbound call metrics
- [x] Implement Micrometer binding with [OkHttp](https://javadoc.io/static/io.micrometer/micrometer-core/1.5.3/io/micrometer/core/instrument/binder/okhttp3/OkHttpMetricsEventListener.html) to automatically collect outbound call metrics
