### ISSUE TITLE
Observability: Tracing: OpenTelemetry

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#36]
EDC Story: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/355
Story for feature agera-edc/DataSpaceConnector#40 

### Description

For tracing calls across applications and tenants, use OpenTelemetry API code and agent as documented at [OpenTelemetry Tracing spike · Agera-CatenaX/EclipseDataSpaceConnector (github.com)](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/blob/spike/open-telemetry/TELEMETRY.md)

We realize that EDC is trying to minimize dependencies, however telemetry is a quite fundamental concept and it seems hard to build a robust solution without such an approach.

### Tasks

- [x] Discussion with Jim to agree on the approach and on the OpenTelemetry library dependency. Agree on which module will declare the OpenTelemetry dependency.
- [x] Create a sample with OpenTelemetry agent and a Jaeger backend running in Docker. The traces from contract negotiation between provider and consumer are visible in Jaeger. The sample README file explains how to modify the config to use Azure Application Insights agent instead
- [x] Set up OpenTelemetry context propagation for *contract negotiation* to extend traces across provider/consumer calls (i.e. save trace headers to the database to be reinjected when requests are processed)
- [x] agera-edc/DataSpaceConnector#57
- [x] Add support for EDC users injecting a custom OpenTelemetry implementation
