### ISSUE TITLE
DevOps: Provide a helm chart to deploy the EDC connector

### ISSUE THREAD

**Issue by ouphi** [agera-edc/DataSpaceConnector#38]
Corresponding EDC issue: [DevOps - Useful - provide Helm charts #432](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/432)

### Description
Provide a helm chart template that can be used to deploy the EDC connector image.
The helm chart needs to be configurable:
  - Configurable env var. The user can pass env var as values.
  - Configurable secrets
  - Configurable labels
  - Configurable annotations

Ingress template:
 - Ingress should be highly configurable

 Testing:
  - The helm chart can be tested with minikube, a local kubernetes. A workflow to test the helm chart needs to be created. It should make sure that CI fails if the helm chart is broken.
  - The helm chart needs to be tested with a suitable EDC configuration to be able to effectively validate deployment, e.g. sample 04.

A [first spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/pull/10) has been done and already covered some of the points

### Tasks
- [x] Provide basic helm chart to deploy the image.
- [x] Add configurable secrets.
- [x] Add configurable labels and annotations.
- [x] Provide configurable ingress template.
- [x] CI to test the helm chart with minikube.
