### ISSUE TITLE
Increase CodeQL Analysis Scope

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#41]
EDC issue: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/648

### Description

EDC currently runs a CodeQL CI workflow executing a reduced set of security queries (~44) to prevent security vulnerabilities. This workflow blocks PRs where vulnerabilities are detected.

CodeQL provides [extended query suites](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs) that provide additional coverage for code quality checks. The goal of this story is to introduce the `security-and-quality` CodeQL suite in the CI workflow to detect bugs and code smells and thus raise code quality level in EDC.

### Acceptance Criteria
- [x] EDC repository uses extended CodeQL queries to detect potential code quality issues
- [x] The build is failed on the agreed level of alerts severity
- [x] Documentation is available

### Tasks
- [x] Use the `security-and-quality` CodeQL suite in the CodeQL workflow
- [x] Agree on minimal alert severity to block PRs
- [x] Suppress low-severity alerts
- [x] Fix existing alerts
- [x] Create separate items to fix alerts that can't be solved right away
- [x] Create/update documentation
- [x] Inform community

See [spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/tree/spike/code-quality-and-test-coverage/docs/codequality) results
