### ISSUE TITLE
Coverage Reports with Jacoco and Codecov

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#42]
EDC issue: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/646
Feature: #50 

### Description

Test coverage is currently not measured in EDC. The goal of this story is to measure test coverage and raise developer awareness by making visible in PRs how the test coverage is impacted by the change.

### Acceptance Criteria
- [x] The test coverage in the project is monitored   
- [x] Test coverage reports are visible in the PRs

### Tasks
- [x] Introduce Jacoco in gradle build
- [x] Setup Codecov for visualizing coverage changes introduced by PRs
- [x] Documentation
- [x] Inform community

See [spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/tree/spike/code-quality-and-test-coverage/docs/codequality) results
