### ISSUE TITLE
Observability: Tracing: OpenTelemetry custom spans and tags

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#48]
Story for feature agera-edc/DataSpaceConnector#40 
EDC issue: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/643

### Description
As an EDC developer I would like to have relevant additional information in traces so that I can analyze operations in the system.

### Acceptance Criteria

- [x] Decide which additional custom spans and tags are relevant for significant EDC internal operations
- [x] Add additional custom spans and tags using open telemetry API

### Tasks

- [x] Write an ADR for custom spans and tags or extend existing ADR for OpenTelemetry
- [x] Align with Jim and Paul about custom spans and tags
- [x] Set up OpenTelemetry custom spans for significant internal operations (e.g. data processor loop steps)
