### ISSUE TITLE
Test Coverage Reports

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#50]
### Description
This feature will introduce test coverage reports and make test coverage metrics easily accessible in pull requests. Having a test coverage report accessible in pull requests enables developers to see how the test coverage is impacted by the change.

### Stories
  - [x] agera-edc/DataSpaceConnector#51 
  - [x] agera-edc/DataSpaceConnector#42 
  - [x] agera-edc/DataSpaceConnector#56
