### ISSUE TITLE
Deployment of Sample 05 to Azure Without Admin Permissions

### ISSUE THREAD

**Issue by ouphi** [agera-edc/DataSpaceConnector#53]
### Description

Sample 05 uses Terraform. In order to create the required resources, the user running `terraform apply` needs to be admin in its azure tenant or have advanced rights. The user needs to have the rights to create a service principal and assign a certificate to an application. A developer is not always admin in its organization tenant. It would be good to adapt the sample such that a user does not need to have elevated privileges.
Another issue is that the sample 05 is broken because some dependencies are needed, which needs to be fixed.

### Acceptance Criteria

- [ ] Sample 05 can be run in Azure without requiring an admin role.

### Tasks

- [ ] Adapt terraform to work even if the user is not admin in his Azure tenant. By using a client secret instead of a certificate.
- [ ] Adapt the README accordingly.
- [ ] Fix sample 05.
