### ISSUE TITLE
Spike - Benchmarking Tools

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#59]
Feature #28 
Before #60 

## Description

The goal of this spike is to evaluate benchmarking tools to establish a benchmarking tool for performance testing.

One option mentioned by Jim was [Java Microbenchmark Harness](https://github.com/openjdk/jmh).

## Acceptance Criteria

- [ ] Evaluate available benchmarking tools, including the JMH
- [ ] Agree with Jim on the tool and approach to use
- [ ] ADR on benchmarking tools is available
- [ ] Follow-up story #60 is refined
- [ ] Additional follow-up stories are created if need be

## Tasks

- [ ] TODO

**Comment by zeier** [comment]
Discarding this story as there were no specific needs at this time.
