### ISSUE TITLE
Evaluate Lint tools

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#67]
### Acceptance Criteria
- [ ] Evaluate available lint
- [ ] Agree with Jim on the tool and rules to use
- [ ] Create an ADR, if required
- [ ] Finalize on the next steps

### Tasks
- [ ]
