### ISSUE TITLE
Code quality: Fine tune Checkstyle rules

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#68]
Feature #32 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/991

## Description

As a contributor I would like to know if my code complies with EDC coding standards.

## Acceptance Criteria

- [x] A proper set of checkstyle rules are used in EDC in agreement with the community
- [x] Failures on agreed checkstyle rules are visible on the PRs.

## Tasks

- [x] Review current Checkstyle ruleset against best practices 
- [x] Discuss potential modifications with Jim and Paul
- [x] Implement modifications to the Checkstyle ruleset if applicable
- [x] Update doc (styleguide.md) doc if applicable

**Comment by algattik** [comment]
JavadocMethod commented out

**Comment by algattik** [comment]
- Checks commented out

```
<!--    disabled javadoc paragraph checking as it would complain about <p> tags-->
<!--    <module name="JavadocParagraph">-->
<!--      <property name="allowNewlineParagraph" value="false"/>-->
<!--    </module>-->

<!-- DISABLED FOR NOW
    <module name="MissingJavadocMethod">
      <property name="scope" value="public"/>
      <property name="minLineCount" value="2"/>
      <property name="allowedAnnotations" value="Override, Test"/>
      <property name="tokens" value="METHOD_DEF, CTOR_DEF, ANNOTATION_FIELD_DEF,
                                   COMPACT_CTOR_DEF"/>
    </module>
    <module name="MissingJavadocType">
      <property name="scope" value="protected"/>
      <property name="tokens"
                value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF,
                      RECORD_DEF, ANNOTATION_DEF"/>
      <property name="excludeScope" value="nothing"/>
    </module>
-->
```

- Additional checks found in https://github.com/Azure/azure-sdk-for-java/blob/main/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml (as used in PRS)

Under Checker:

```
  <module name="SuppressWarningsFilter" />

  <module name="Header">
    <property name="header" value="..."/>
    <property name="fileExtensions" value="java"/>
  </module>

  <module name="NewlineAtEndOfFile" />

  <module name="RegexpSingleline">
    <!-- Checks that FIXME is not used in comments.  TODO is preferred. -->
    <property name="format" value="((//.*)|(\*.*))FIXME"/>
    <property name="message" value='TODO is preferred to FIXME.  e.g. "TODO(johndoe): Refactor when v2 is released."'/>
  </module>

  <module name="RegexpSingleline">
    <!-- Checks that TODOs are named.  (Actually, just that they are followed by an open paren. -->
    <property name="format" value="((//.*)|(\*.*))TODO [^(]"/>
    <property name="message" value='All TODOs should be named.  e.g. "TODO (johndoe): Refactor when v2 is released."'/>
  </module>
```

Under Checker/TreeWalker:

```
    <module name="AvoidNestedBlocks"/>
    <module name="ConstantNameCheck">
      <!-- Validates non-private, static, final fields against the supplied
      public/package final fields "^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$". -->
      <metadata name="altname" value="ConstantName"/>
      <property name="applyToPublic" value="true"/>
      <property name="applyToProtected" value="true"/>
      <property name="applyToPackage" value="true"/>
      <property name="applyToPrivate" value="false"/>
      <property name="format" value="^([A-Z][A-Z0-9]*(_[A-Z0-9]+)*|FLAG_.*)$"/>
      <message key="name.invalidPattern"
               value="Variable ''{0}'' should be in ALL_CAPS (if it is a constant) or be private (otherwise)."/>
      <property name="severity" value="warning"/>
    </module>
    <module name="EmptyForIteratorPad"/>
    <module name="EmptyStatement"/>
    <module name="EqualsHashCode"/>
    <module name="FinalClass"/>
    <module name="IllegalImport">
      <property name="regexp" value="true"/>
      <property name="illegalPkgs" value="^(com\.)?sun\.\w*, ^io.opentelemetry"/>
    </module>
    <module name="IllegalInstantiation"/>
    <module name="InnerAssignment"/>
    <module name="InterfaceIsType"/>
    <module name="LocalFinalVariableName"/>
    <module name="MagicNumber" />
    <module name="MemberNameCheck">
      <!-- Validates non-static members against the supplied expression. -->
      <metadata name="altname" value="MemberName"/>
      <property name="applyToPublic" value="true"/>
      <property name="applyToProtected" value="true"/>
      <property name="applyToPackage" value="true"/>
      <property name="applyToPrivate" value="true"/>
      <property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
      <property name="severity" value="warning"/>
    </module>
    <module name="MethodNameCheck">
      <!-- Validates identifiers for method names. -->
      <metadata name="altname" value="MethodName"/>
      <property name="format" value="^[a-z][a-zA-Z0-9]*(_[a-zA-Z0-9]+)*$"/>
      <property name="severity" value="warning"/>
    </module>
    <module name="MissingDeprecated"/>
    <module name="MissingJavadocPackage"/>
    <module name="NoWhitespaceAfter">
      <property name="tokens" value="INC,DEC,UNARY_MINUS,UNARY_PLUS,BNOT,LNOT,DOT,ARRAY_DECLARATOR,INDEX_OP"/>
    </module>
    <module name="RedundantImport"/>
    <module name="RedundantModifier"/>
    <module name="StaticVariableName"/>
    <module name="StaticVariableNameCheck">
      <metadata name="altname" value="StaticVariableName"/>
      <property name="applyToPublic" value="true"/>
      <property name="applyToProtected" value="true"/>
      <property name="applyToPackage" value="true"/>
      <property name="applyToPrivate" value="true"/>
      <property name="format" value="^[a-z][a-zA-Z0-9]*_?$"/>
      <property name="severity" value="warning"/>
    </module>
    <module name="TypeNameCheck">
      <metadata name="altname" value="TypeName"/>
      <property name="severity" value="warning"/>
    </module>
    <module name="TypecastParenPad"/>
    <module name="UnusedImports"/>
    <module name="VisibilityModifier">
      <property name="protectedAllowed" value="true"/>
      <property name="packageAllowed" value="true"/>
    </module>
    <module name="SuppressWarningsHolder" />
```

**Comment by cpeeyush** [comment]
> * Checks commented out
> 
> ```
> 
> 
> 
> 
> 
> 
> ```
> 
> * Additional checks found in https://github.com/Azure/azure-sdk-for-java/blob/main/eng/code-quality-reports/src/main/resources/checkstyle/checkstyle.xml (as used in PRS)
> 
> Under Checker:
> 
> ```
>   <module name="SuppressWarningsFilter" />
> 
>   <module name="Header">
>     <property name="header" value="..."/>
>     <property name="fileExtensions" value="java"/>
>   </module>
> 
>   <module name="NewlineAtEndOfFile" />
> 
>   <module name="RegexpSingleline">
>     
>     <property name="format" value="((//.*)|(\*.*))FIXME"/>
>     <property name="message" value='TODO is preferred to FIXME.  e.g. "TODO(johndoe): Refactor when v2 is released."'/>
>   </module>
> 
>   <module name="RegexpSingleline">
>     
>     <property name="format" value="((//.*)|(\*.*))TODO [^(]"/>
>     <property name="message" value='All TODOs should be named.  e.g. "TODO (johndoe): Refactor when v2 is released."'/>
>   </module>
> ```
> 
> Under Checker/TreeWalker:
> 
> ```
>     <module name="AvoidNestedBlocks"/>
>     <module name="ConstantNameCheck">
>       
>       <metadata name="altname" value="ConstantName"/>
>       <property name="applyToPublic" value="true"/>
>       <property name="applyToProtected" value="true"/>
>       <property name="applyToPackage" value="true"/>
>       <property name="applyToPrivate" value="false"/>
>       <property name="format" value="^([A-Z][A-Z0-9]*(_[A-Z0-9]+)*|FLAG_.*)$"/>
>       <message key="name.invalidPattern"
>                value="Variable ''{0}'' should be in ALL_CAPS (if it is a constant) or be private (otherwise)."/>
>       <property name="severity" value="warning"/>
>     </module>
>     <module name="EmptyForIteratorPad"/>
>     <module name="EmptyStatement"/>
>     <module name="EqualsHashCode"/>
>     <module name="FinalClass"/>
>     <module name="IllegalImport">
>       <property name="regexp" value="true"/>
>       <property name="illegalPkgs" value="^(com\.)?sun\.\w*, ^io.opentelemetry"/>
>     </module>
>     <module name="IllegalInstantiation"/>
>     <module name="InnerAssignment"/>
>     <module name="InterfaceIsType"/>
>     <module name="LocalFinalVariableName"/>
>     <module name="MagicNumber" />
>     <module name="MemberNameCheck">
>       
>       <metadata name="altname" value="MemberName"/>
>       <property name="applyToPublic" value="true"/>
>       <property name="applyToProtected" value="true"/>
>       <property name="applyToPackage" value="true"/>
>       <property name="applyToPrivate" value="true"/>
>       <property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
>       <property name="severity" value="warning"/>
>     </module>
>     <module name="MethodNameCheck">
>       
>       <metadata name="altname" value="MethodName"/>
>       <property name="format" value="^[a-z][a-zA-Z0-9]*(_[a-zA-Z0-9]+)*$"/>
>       <property name="severity" value="warning"/>
>     </module>
>     <module name="MissingDeprecated"/>
>     <module name="MissingJavadocPackage"/>
>     <module name="NoWhitespaceAfter">
>       <property name="tokens" value="INC,DEC,UNARY_MINUS,UNARY_PLUS,BNOT,LNOT,DOT,ARRAY_DECLARATOR,INDEX_OP"/>
>     </module>
>     <module name="RedundantImport"/>
>     <module name="RedundantModifier"/>
>     <module name="StaticVariableName"/>
>     <module name="StaticVariableNameCheck">
>       <metadata name="altname" value="StaticVariableName"/>
>       <property name="applyToPublic" value="true"/>
>       <property name="applyToProtected" value="true"/>
>       <property name="applyToPackage" value="true"/>
>       <property name="applyToPrivate" value="true"/>
>       <property name="format" value="^[a-z][a-zA-Z0-9]*_?$"/>
>       <property name="severity" value="warning"/>
>     </module>
>     <module name="TypeNameCheck">
>       <metadata name="altname" value="TypeName"/>
>       <property name="severity" value="warning"/>
>     </module>
>     <module name="TypecastParenPad"/>
>     <module name="UnusedImports"/>
>     <module name="VisibilityModifier">
>       <property name="protectedAllowed" value="true"/>
>       <property name="packageAllowed" value="true"/>
>     </module>
>     <module name="SuppressWarningsHolder" />
> ```

@algattik I didn't understand. You propose to enable these additional checks ?

**Comment by algattik** [comment]
Was just making a note of possible things to look at :)

**Comment by algattik** [comment]
Creating multiple PRs:
- Header (large scale fix in code base)
- Unused import
- Misc rules

The following rules (from Azure Java SDK) can be considered in addition. Probably we should raise PRs for those except the last two ones.

Rule | Number of violations in EDC
-- | --
MissingDeprecated | 1
VisibilityModifier | 2
InnerAssignment | 3
StaticVariableName | 10
InterfaceIsType | 21
RedundantModifier | 42
UnusedImports | 57
FinalClass | 178
MagicNumber | 815

**Comment by algattik** [comment]
Multiple PRs opened upstream - see upstream issue for links to them https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/991
