### ISSUE TITLE
Code quality: Evaluate inter-module automatic dependency checks

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#79]
Feature #32
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/827

### Description

As an EDC contributor I would like to know, if my code is creating forbidden dependencies between modules so that I can prevent them. See upstream EDC story for sample use cases.

### Acceptance Criteria
- [ ] Proposal for a mechanism for detecting forbidden module dependencies
- [ ] Rules for forbidden dependencies can be codified with the proposed solution.
- [ ] Rules described in the upstream issues can be implemented

### Tasks
- [ ] Evaluate candidates: eg. JDepend, Dependapot, Classycle, Spotbugs
- [ ] Document tools evaluation
- [ ] Propose most feasible tool to determine dependency checks in EDC code
- [ ] Add details to the follow up story #89

**Comment by algattik** [comment]
examples:
- a `:core:*` module cannot depend on a `:extension:*` module
- an SPI module cannot depend on an implementation module

Jim will write up in EDC repo.

**Comment by algattik** [comment]
The proposed tools were for *code analysis*, but from the rules eventually provided by Paul the scope actually turned out to be *static build analysis* and the tools in question don't apply.

**Comment by marcgs** [comment]
> The proposed tools were for _code analysis_, but from the rules eventually provided by Paul the scope actually turned out to be _static build analysis_ and the tools in question don't apply.

The proposed tools were just an initial suggestion, its perfectly fine to have chosen the right tools according to the rules provided by Paul. Regarding the follow-up story #89, is it still required? To me it looks like the work done in this spike covers the requirements.

**Comment by marcgs** [comment]
Updated #89 according to outputs of this spike
