### ISSUE TITLE
System tests for EDC core: folder structure and load setup

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#81]
Feature: #28 
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/783, https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/829

## Description

We built a system test around sample 4 to test end-to-end flow across application instances. However, system tests should have a different lifecycle than samples. They should be able to be scaled up for performance testing. Samples should remain as simple as possible for new users to understand the behaviour of EDC.

- Move system test out of the samples directory. Create new projects under root `system-tests` directory. System tests should use their own set of `launchers` to configure EDC applications to run (e.g. sample 4 consumer EDC instance and provider EDC instance). Do not "pollute" the root  `launchers` directory with system-test specific stuff.
- Wrap client call with Gatling to build an illustrative load test set up. The load test should run as fast as possible (i.e. for a single query), but be configurable to run higher load tests manually.

Note: DPF is not yet integrated in the system test.

Note: there is no new test code or logic to write (except to bind into Gatling).

## Acceptance Criteria
- [x] ADR on load testing
- [x] System test established in root `system-tests` directory
- [x] System test runs in CI
- [x] System test uses Gatling
- [x] Gatling report published in CI (optional - if feasible)
- [x] Document how to implement and run load test
- [x] Sample 4 directory does not include automated testing

## Tasks
- [x] Write ADR
- [x] Refactor system tests
- [x] Introduce Gatling
- [x] Adapt CI

**Comment by algattik** [comment]
Blocked by upstream 701 (helm charts system test)
