### ISSUE TITLE
Resilience: Cosmos DB HA tests

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#82]
EDC Repo: [#423](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/423)

Cosmos DB stores for managing contract negotiations and data transfers contain complex distributed logic is stored procedures. This logic should be documented and properly tested in a distributed setup.

## Background

If a provider connector fails after receiving a request, a transfer process needs to be picked up by another provider connector instance. This is specially important when deploying to Kubernetes, since pods can be restarted at any time (e.g. VM autoscale).

A TransferProcessStore backed by an external storage is required to achieve this. In addition a transfer process leasing mechanism to orchestrate the assignment of transfer processes to provider connector instances needs to be in place as well.

A CosmosDB-based solution is partially implemented in EDC. This solution requires two stored procedures which are available in test resources. The stored procedures contain in-built logic to automatically extend leases when data is fetched, and to take over leases after timeout. The stored procedures are not documented and understanding the logic is not obvious.

*Note:* There are multiple javascript stored procedures in the repository, with partially redundant content. Streamlining this is out of scope of this issue, and should be done after this test harness is put in place.

## Acceptance Criteria

- [ ] An ADR documents the behaviour implemented in the Cosmos DB stored procedures, retroactively analysing the decisions that were made. It explains the implementation, and how internal transactional mechanism is used to ensure an item with an expired lease is only acquired by one instance, in a concurrency scenario.
- [ ] Integration tests run against Cosmos DB to deploy the stored procedure and spin multiple instances to verify that an item with an expired lease is picked up by another instance after timeout.

## Tasks

- [ ] Write ADR
- [ ] Write basic integration test (without checking for failover) that deploys the stored procedure and performs one contract negotiation and one data transfer with a single instance, using the Cosmos DB backend. (Hint: reuse the client code in `FileTransferTestUtils` from https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/701)
- [ ] Adapt integration test to run multiple instances and inject faults to test failover, in both the contract negotiation and data transfer loops

**Comment by chrislomonico** [comment]
Assigned for refinement (@cpeeyush @algattik)
As discussed, 3 stories will be removed and combined into a single feature for starting point

**Comment by algattik** [comment]
Merged into #70

**Comment by cpeeyush** [comment]
waiting for outcome of spike #183
