### ISSUE TITLE
Resilience: Consumer must reattempt transfers when Provider not available

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#83]
Feature #70 
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/336

If the Consumer calls `TransferProcessManager#initiateConsumerRequest` but the Provider is not available, the Consumer does not receive an error. If the Provider later becomes available, the request does not get processed. The transfer process remains in its state and does not get advanced.

### Acceptance criteria

- [ ] Data transfers are guaranteed to eventually complete, or move to `ERROR` state, even if the Provider becomes unavailable for an extended duration at any state of transfer (during initiation or afterwards). This applies to retriable error (e.g. server not available, Internal server error response).
- [ ] In case the Provider returns a non-retriable error (e.g. unauthorised or bad request), the transfer is immediately moved to a terminal state and is not further retried.
- [ ] Integration tests exists for non-regression.

### Tasks

- [ ] Evaluate and propose an implementation change, validate with Jim and Paul.
- [ ] Develop an integration test demonstrating the problem. The test should fail.
- [ ] Implement the change and adapt unit tests. Ensure the integration test passes.

**Comment by chrislomonico** [comment]
Assigned for refinement (@cpeeyush @algattik)
As discussed, 3 stories will be removed and combined into a single feature for starting point

**Comment by algattik** [comment]
Architecture - Essential - "at-least-once" TransferProcessListener #70

**Comment by algattik** [comment]
Started discussion in upstream issue, needs decision in order to progress

**Comment by zeier** [comment]
Putting this story on hold until blockers are removed and Alexandre is back.

**Comment by chrislomonico** [comment]
Marking as closed, per comments on upstream
