### ISSUE TITLE
Code quality: inter-module automatic dependency checks

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/DataSpaceConnector#89]
Feature #32
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/827

### Description

As an EDC contributor I would like to know, if my code is creating forbidden dependencies between modules so that I can prevent them. See upstream EDC story for sample use cases.

Use approach from spike #160 .

Remaining work to be done are small cleanups from what has been done in #160.

### Acceptance Criteria
- [x] A mechanism for detecting forbidden module dependencies is in place
- [x] Forbidden module dependencies are checked during CI
- [x] It is configurable whether forbidden module dependencies will be logged or whether they fail the build

### Tasks
- [x] Introduce selected mechanism in EDC repo based on #79 
- [x] Clean up custom gradle task by extracting it from main build file (see https://docs.gradle.org/current/userguide/custom_tasks.html#sec:packaging_a_task_class)
- [ ] Unit test custom gradle task

**Comment by arckumari** [comment]
depends on spike outcomes #79

**Comment by chrislomonico** [comment]
closing per upstream status
