### ISSUE TITLE
CI/Testing: Use Cosmos DB emulator in CI

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#91]
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/360
Feature: #30

### Description
Cosmos DB [extension](https://github.com/agera-edc/DataSpaceConnector/tree/main/extensions/azure/cosmos) integration tests use a pre-configured azure Cosmos DB instance which requires specific account/container setup. It is also disabled on forks, because a secret is needed, and we did not want to force such forks to set up such an instance.

Rather than using Azure Cosmos DB instance, a docker based Cosmos DB Emulator([Linux](https://docs.microsoft.com/en-us/azure/cosmos-db/linux-emulator?tabs=ssl-netstd21)) can be used.

Note: (Cosmos db testcontainer [module ](https://www.testcontainers.org/modules/azure/)is also available)

### Acceptance Criteria

- [x] Cosmos DB based integration test runs against docker emulator.
- [x] CI pipeline uses docker emulator to run Cosmos DB tests.
- [x] CI pipeline runs Cosmos DB tests also on forks.

### Tasks

- [ ] todo

**Comment by algattik** [comment]
Working already ongoing in upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/721

**Comment by algattik** [comment]
Pulled issue into the sprint since another developer has started work on this and requested our help

**Comment by algattik** [comment]
Implemented using emulator on Windows, rather than Docker on Linux, due to stability issues.
