### ISSUE TITLE
CI/Testing: Stabilize unit tests 

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#92]
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/728
Feature: https://github.com/agera-edc/DataSpaceConnector/issues/30

Unit (and also some integration) tests are regularly failing in CI. This is limiting our flow.

Examples:

```

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5203062272?check_suite_focus=true

MultipartDispatcherIntegrationTest > testSendContractAgreementMessage() FAILED
AtomikosTransactionExtensionTest > verifyEndToEndTransactions() FAILED
MultipartControllerIntegrationTest > testRequestConnectorSelfDescriptionWithoutId() FAILED

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/runs/1865086145

:extensions:catalog:federated-catalog-cache:test > LoaderManagerImplTest FAILED

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5248995730?check_suite_focus=true

:extensions:azure:cosmos:assetindex-cosmos:test > CosmosAssetIndexIntegrationTest > queryAssets_operatorIn_noBrackets_throwsException() FAILED

```

## Acceptance Criteria

- [x] CI Pipeline succeeds consistently when executed a large number of times

## Tasks

- [x] Analyse logs of past builds to determine statistics on which tests have been failing
- [x] Analyse and resolve root cause
- [ ] Update test document with best practices
- [x] Propose working agreement that a flaky test should immediately lead to a high priority issue filed in EDC repo

**Comment by algattik** [comment]
Created a fork and removed all workflows except the unit test job.
Running 100 CI builds:

```
for i in $(seq 1 100); do
  b=test$i
  git checkout -b $b ut
  git push --set-upstream origin $b
done
```

```
gh run list --workflow verify.yaml --limit 100 -R algattik/DataSpaceConnector --json databaseId -q '.[] | .databaseId' | xargs -n1 gh run view --log-failed > log
cat log|grep -i failed|cut -f3-|cut -f2- -d ' '|sort|uniq -c|sort -nr                             

  17 FAILURE: Build failed with an exception.
  10 JerseyRestServiceTest > Verifies that a resource is available under the default path FAILED
  10 Execution failed for task ':extensions:http:jersey:test'.
  10 > Task :extensions:http:jersey:test FAILED
  10 9 tests completed, 1 failed
   9     org.opentest4j.AssertionFailedError
   6 Execution failed for task ':extensions:api:data-management:contractnegotiation:test'.
   6 ContractNegotiationApiControllerIntegrationTest > getAllContractNegotiations() FAILED
   6 > Task :extensions:api:data-management:contractnegotiation:test FAILED
   6 30 tests completed, 1 failed
   3 31 tests completed, 1 failed
   3 2: Task failed with an exception.
   3 1: Task failed with an exception.
   2 PolicyApiControllerIntegrationTest > getSinglePolicy() FAILED
   2 Execution failed for task ':extensions:azure:vault:compileTestJava'.
   2 Execution failed for task ':extensions:api:data-management:policydefinition:test'.
   2 BUILD FAILED in 12m 24s
   2 > Task :extensions:azure:vault:compileTestJava FAILED
   2 > Task :extensions:api:data-management:policydefinition:test FAILED
   2       > Failed to list versions for com.microsoft.azure:azure-client-runtime.
   1 TransferProcessApiControllerIntegrationTest > getSingleTransferProcess_notFound() FAILED
   1 LoaderManagerImplTest > Verify that the loader manager waits one pass when the queue does not yet contain sufficient elements FAILED
   1 Execution failed for task ':extensions:catalog:federated-catalog-cache:test'.
   1 Execution failed for task ':extensions:api:data-management:transferprocess:test'.
   1 Execution failed for task ':extensions:api:data-management:contractdefinition:test'.
   1 Execution failed for task ':extensions:api:data-management:asset:test'.
   1 Execution failed for task ':data-protocols:ids:ids-api-multipart-dispatcher-v1:test'.
   1 ContractDefinitionsApiControllerIntegrationTest > getSingleContractDef_notFound() FAILED
   1 BUILD FAILED in 7m 59s
   1 BUILD FAILED in 7m 17s
   1 BUILD FAILED in 7m
   1 BUILD FAILED in 14m 31s
   1 BUILD FAILED in 13m 49s
   1 BUILD FAILED in 13m 3s
   1 BUILD FAILED in 13m 21s
   1 BUILD FAILED in 13m 18s
   1 BUILD FAILED in 13m 14s
   1 BUILD FAILED in 12m 8s
   1 BUILD FAILED in 12m 42s
   1 BUILD FAILED in 11m 5s
   1 BUILD FAILED in 11m 1s
   1 BUILD FAILED in 10m 57s
   1 BUILD FAILED in 10m 38s
   1 BUILD FAILED in 10m 29s
   1 BUILD FAILED in 10m 28s
   1 BUILD FAILED in 10m 12s
   1 AssetControllerIntegrationTest > deleteAsset() FAILED
   1 > Task :extensions:catalog:federated-catalog-cache:test FAILED
   1 > Task :extensions:api:data-management:transferprocess:test FAILED
   1 > Task :extensions:api:data-management:contractdefinition:test FAILED
   1 > Task :extensions:api:data-management:asset:test FAILED
   1 > Task :data-protocols:ids:ids-api-multipart-dispatcher-v1:test FAILED
   1 4: Task failed with an exception.
   1 3: Task failed with an exception.
   1 26 tests completed, 1 failed
   1 23 tests completed, 1 failed
   1 18 tests completed, 1 failed
   1     org.opentest4j.AssertionFailedError: 
   1         java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:44593
   1                > Connect to maven.iais.fraunhofer.de:443 [maven.iais.fraunhofer.de/193.175.162.89] failed: connect timed out
   1                > Connect to maven.iais.fraunhofer.de:443 [maven.iais.fraunhofer.de/193.175.162.89] failed: Read timed out
```

**Comment by marcgs** [comment]
Running 100 CI workflows on my private fork results:

```
gh run list --workflow verify.yaml --limit 100 -R marcgs/DataSpaceConnector --json databaseId -q '.[] | .databaseId' | xargs -n1 gh run view -R marcgs/DataSpaceConnector --log-failed  > log
```

```
   4 FAILURE: Build failed with an exception.
   1 HealthCheckServiceImplTest > isReady_throwsException() FAILED
   1 Execution failed for task ':samples:other:streaming:test'.
   1 Execution failed for task ':extensions:azure:vault:compileTestJava'.
   1 Execution failed for task ':data-protocols:ids:ids-api-multipart-endpoint-v1:test'.
   1 Execution failed for task ':core:base:test'.
   1 DemoPushStreamTransferTest > verifyWsPushStreamFlow(TransferProcessManager, TopicManager, DataOperatorRegistry, Monitor, Vault, OkHttpClient, TypeManager) FAILED
   1 BUILD FAILED in 7m 56s
   1 BUILD FAILED in 17m 26s
   1 BUILD FAILED in 15m 4s
   1 BUILD FAILED in 11m 55s
   1 > Task :samples:other:streaming:test FAILED
   1 > Task :extensions:azure:vault:compileTestJava FAILED
   1 > Task :data-protocols:ids:ids-api-multipart-endpoint-v1:test FAILED
   1 > Task :core:base:test FAILED
   1 6 tests completed, 1 failed
   1 10 tests completed, 1 failed
   1     org.opentest4j.AssertionFailedError:
   1       > Failed to list versions for com.microsoft.azure:azure-client-runtime.
   1                > Connect to maven.iais.fraunhofer.de:443 [maven.iais.fraunhofer.de/193.175.162.89] failed: connect timed out
```

**Comment by marcgs** [comment]
Contribution guidelines extended for flaky tests: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/769/files
