### ISSUE TITLE
CI: CodeQL is slow

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#95]
##  Description

CodeQL runs for every PR and takes 22+ minutes. This is a hindrance for flow.
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/actions/workflows/codeql-analysis.yml

## Acceptance Criteria

- [ ] CodeQL runtime runs with acceptable performance (~10mins)
- [ ] A decision is taken with Paul & Jim how to proceed with a slow CodeQL pipeline if improvement not possible

## Tasks
- [ ] Investigate ways to make CodeQL pipeline faster
  - [ ] Incremental generation of CodeQL DB
  - [ ] Caching of CodeQL DB
  - [ ] Repo split (several CodeQL pipelines for different parts of EDC)
  - [ ] Others

**Comment by chrislomonico** [comment]
I see some higher times the analysis, but is 22 min avg?  Seems a bit of an extreme either way.  While this should be addressed, we need to find the right solution.  This may be a symptom indicating a different problem

**Comment by algattik** [comment]
Solved by #692 which reduces duration to 8-12 min.
