### ISSUE TITLE
DPF: Manage Thread Pool

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#96]
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/618
Story for feature agera-edc/DataSpaceConnector#20 

## Description

In #85 I've copied this line from the HTTP sink to the Blob storage sink:
```
        var executorService = Executors.newFixedThreadPool(10); // TODO make configurable
```

We probably want to share this pool across services.

## Acceptance Criteria

- [x] Approach on how to share the thread pool across services is defined
- [x] Shared thread pool is used in the line of code mentioned above

## Tasks

- [x] Create EDC issue with intended approach
- [x] Add shared thread pool 
- [x] Use the shared thread pool in the 2 extensions: DataPlaneAzureStorageExtension & DataPlaneHttpExtension

**Comment by algattik** [comment]
Needs upstream PR 912
